# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-22 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20170422_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='content',
            new_name='query_string',
        ),
    ]
