# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20170422_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'get_latest_by': 'search_date', 'ordering': ['search_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='content',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='query',
            new_name='question',
        ),
        migrations.AddField(
            model_name='query',
            name='search_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='source',
            field=models.URLField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=31, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
    ]
