# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20170429_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='slug',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='source',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(related_name='snippets', to='archive.Tag'),
        ),
    ]
